Algoritmo "Algoritmo5"

Var
   a, b, c, del : real
Inicio
   //Entradas
   escreval("Discriminante (delta) de uma equação de segundo grau")
   escreval("ax² + bx + c = 0")
   escreval("Digite o valor de a:")
   leia(a)
      escreval("Digite o valor de b:")
   leia(b)
      escreval("Digite o valor de c:")
   leia(c)
   //Processamento
   del <- b^2 - 4 * a * c
   //Saida
   escreval("Valor do discriminante (delta) = ",del)
   
Fimalgoritmo