Algoritmo "Segundo Algoritimo"

Var
   num1, num2, soma : inteiro
Inicio
   // algoritimo que soma dois numeros inteiros
   //Entrada
   escreval("soma de dois numeros inteiros")
   escreval("Digite o 1° número inteiro")
   leia(num1)
   escreval("Digite o 2° número inteiro")
   leia(num2)
   //Processamento
   soma <- num1 + num2
   //Saída
   escreval("A soma vale:", soma)
   escreval(num1," +",num2," =", soma)
Fimalgoritmo